# Generated by Django 3.1 on 2020-08-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_start', models.DateField()),
                ('project_end', models.DateField()),
                ('project_author', models.CharField(max_length=50)),
            ],
        ),
    ]
