# Generated by Django 3.1 on 2020-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_image', models.ImageField(upload_to='')),
                ('post_brief', models.TextField()),
                ('post_content', models.TextField()),
                ('post_publish_date', models.DateField()),
                ('post_author', models.CharField(max_length=20)),
                ('post_category', models.CharField(max_length=10)),
            ],
        ),
    ]
