# Generated by Django 3.1 on 2020-08-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100)),
                ('comment_content', models.TextField()),
                ('comment_author_id', models.CharField(max_length=100)),
                ('comment_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
